import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, CheckCircle2, Mail, RefreshCw, XCircle } from "lucide-react";
import { createClient } from "../../../lib/supabase/server";
import NotificationRetry from "./NotificationRetry";
import "../admin.css";

export default async function NotificationsPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/admin/login"); const {data:profile}=await supabase.from("admin_profiles").select("id").eq("id",user.id).maybeSingle(); if(!profile)redirect("/admin/login?unauthorized=1");
 const {data:logs}=await supabase.from("consultation_notifications").select("id,consultation_id,notification_type,recipient,subject,status,provider_id,error_message,sent_at,created_at,consultation:consultations(reference,full_name)").order("created_at",{ascending:false}).limit(100);
 const rows=logs??[]; const sent=rows.filter(x=>x.status==="sent").length, failed=rows.filter(x=>x.status==="failed").length;
 return <main className="admin-page"><header className="admin-detail-hero"><Link href="/admin" className="admin-back"><ArrowLeft size={17}/>Back to dashboard</Link><div className="admin-detail-title"><div><span className="consult-panel__eyebrow">Communications</span><h1>Notification center</h1><p>Audit consultation reminders and email delivery activity.</p></div></div></header><section className="admin-stats"><article><Mail/><span>Recent notifications</span><strong>{rows.length}</strong></article><article><CheckCircle2/><span>Sent</span><strong>{sent}</strong></article><article><XCircle/><span>Failed</span><strong>{failed}</strong></article><article><RefreshCw/><span>Retryable</span><strong>{failed}</strong></article></section><section className="admin-table-card"><div className="admin-section-head"><div><span className="consult-panel__eyebrow">Delivery log</span><h2>Recent communications</h2></div><span className="admin-muted">Latest 100 reminder records</span></div>{rows.length===0?<div className="admin-empty"><Mail size={30}/><h3>No reminder notifications yet</h3><p>Confirmed appointments will appear here after the reminder service processes them.</p></div>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Client</th><th>Notification</th><th>Recipient</th><th>Status</th><th>Time</th><th></th></tr></thead><tbody>{rows.map((item:any)=><tr key={item.id}><td><strong>{item.consultation?.full_name||"Client"}</strong><small>{item.consultation?.reference||"—"}</small></td><td>{item.subject}<small>{item.notification_type.replaceAll("_"," ")}</small></td><td>{item.recipient}</td><td><span className={`admin-notification-status is-${item.status}`}>{item.status}</span>{item.error_message&&<small title={item.error_message}>Delivery error recorded</small>}</td><td>{new Date(item.sent_at||item.created_at).toLocaleString()}</td><td>{item.status==="failed"?<NotificationRetry id={item.id}/>:item.consultation_id?<Link className="admin-open" href={`/admin/consultations/${item.consultation_id}`}>Open →</Link>:null}</td></tr>)}</tbody></table></div>}</section></main>
}
