"use client";

import { motion, useInView } from "framer-motion";
import { ArrowLeft, ArrowRight, Award, Building2, ChevronUp, HeartHandshake, Landmark, Linkedin, LockKeyhole, Mail, MapPin, Menu, MessageCircle, Route, SearchCheck, X, Zap } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

const reveal = { initial:{opacity:0,y:28}, whileInView:{opacity:1,y:0}, viewport:{once:true,amount:0.18}, transition:{duration:0.72,ease:[0.22,0.61,0.36,1]} } as const;
const navItems=[{href:"#about",label:"Why Brix Legal"},{href:"#mission",label:"Mission"},{href:"#practice",label:"Practice Areas"},{href:"#team",label:"Our Team"},{href:"#insights",label:"Insights"},{href:"#careers",label:"Careers"},{href:"#contact",label:"Contact"}];
const reasons=[
{id:"seamless-practice",title:"Seamless Practice",description:"We make your legal process as smooth and hassle-free as possible, from first consultation to final resolution.",icon:Route},
{id:"client-centred",title:"Client-Centred",description:"We pride ourselves on nurturing relationships, giving clients the best experience and ensuring partnership longevity.",icon:HeartHandshake},
{id:"legal-expertise",title:"Legal Expertise",description:"Informed guidance and opinions drawn from extensive experience across the corporate and commercial sector.",icon:Award},
{id:"legacy-building",title:"Legacy Building",description:"We structure your business, assets and agreements to stand the test of time and transition seamlessly.",icon:Landmark},
{id:"detail-oriented",title:"Detail-Oriented",description:"A thorough, meticulous approach crafted with care — so that no detail ever goes unnoticed.",icon:SearchCheck},
{id:"attorney-client-privilege",title:"Attorney-Client Privilege",description:"All confidential communications conducted to provide legal advice are duly and rigorously protected.",icon:LockKeyhole},
{id:"corporate-governance",title:"Corporate Governance",description:"We help businesses establish sound governance — accountability, transparency and compliance at every level.",icon:Building2},
{id:"quick-legal-solutions",title:"Quick Legal Solutions",description:"Prompt solutions when you need them — reach us by email, WhatsApp or a scheduled appointment.",icon:Zap}];
const practiceAreas=[["Corporate Practice","Incorporation, structuring and lifecycle advisory."],["Commercial Law","Contracts, transactions and commercial advisory."],["Regulatory & Statutory Compliance","Staying compliant with evolving regulation."],["Alternative Dispute Resolution","Arbitration, mediation and negotiated settlement."],["Taxation Law","Tax planning, advisory and compliance."],["Real Estate & Property Law","Acquisition, title, leases and property counsel."],["Employment Law","Workforce policy, contracts and disputes."],["Intellectual Property","Trademarks, copyright and IP protection."],["Business Structuring & Management","Governance frameworks and operational structure."],["Legacy Building","Succession, estates and enduring structures."],["Media & Entertainment Law","Rights, licensing and creative-industry counsel."],["Litigation","Robust representation before the courts."],["Social Justice","Advancing fairness and equitable outcomes."],["General Legal Counsel","Everyday advisory across your legal needs."]] as const;
const processSteps=[["01","Consultation","We listen first. Book a free consultation to share your matter."],["02","Assessment","We review the facts, risks and options in meticulous detail."],["03","Strategy","We design a clear, compliant path tailored to your goals."],["04","Execution","We handle filings, negotiations and representation on your behalf."],["05","Resolution","We deliver seamless outcomes designed to stand the test of time."]] as const;
const openRoles=[["Associate Counsel","Corporate & Commercial"],["Compliance Lead","Regulatory & Statutory"],["Litigation Associate","Dispute Resolution"],["Legal Intern","Trainee Programme"]] as const;
const testimonials=[{company:"Air Sea Freighters Ltd",initials:"AS",sector:"Logistics",quote:"Brix Legal excels in statutory compliance, and we highly recommend their services."},{company:"Vitamins Farm Ltd",initials:"VF",sector:"Agriculture",quote:"Brix Legal has consistently provided outstanding legal advisory, ensuring our legal protection at all times."},{company:"Now Now Dispatch",initials:"NN",sector:"Delivery",quote:"We have had a commendable experience with Brix Legal. We appreciate their expertise in the legal field."},{company:"Feed a Hungry Child Foundation",initials:"FH",sector:"Non-Profit",quote:"Brix Legal managed our incorporation quickly and efficiently — always available for consultation and seamless practice."},{company:"Body Type",initials:"BT",sector:"Wellness",quote:"We received outstanding legal advice from the Brix Legal team — it has been crucial to our growth as a business."},{company:"OA Rattan Ng.",initials:"OA",sector:"Manufacturing",quote:"Brix Legal has supported us from incorporation to compliance and counsel. We appreciate their attention to detail."},{company:"Xsealz Ltd",initials:"XZ",sector:"Trade",quote:"The legal process with Brix Legal has been seamless and hassle-free from start to finish."},{company:"Bélle by Brie",initials:"BB",sector:"Fashion",quote:"Brix Legal has been essential to our growth — they are our one-stop compliance hub."}];
const clientNames=testimonials.map(({company})=>company);
function Brand({compact=false}:{compact?:boolean}){return <span className={compact?"brand brand--compact":"brand"}><img src="/brix-legal-emblem.webp" alt="" aria-hidden="true"/><span><strong>Brix Legal</strong><small>Practice &amp; Consultancy</small></span></span>}
function SectionLabel({children}:{children:React.ReactNode}){return <p className="section-label">{children}</p>}
function Counter({value,suffix=""}:{value:number;suffix?:string}){const ref=useRef<HTMLSpanElement>(null);const inView=useInView(ref,{once:true,amount:.75});const [displayValue,setDisplayValue]=useState(0);useEffect(()=>{if(!inView)return;let frame=0;let startTime:number|undefined;const duration=1400;const animate=(time:number)=>{startTime??=time;const progress=Math.min((time-startTime)/duration,1);const eased=1-Math.pow(1-progress,3);setDisplayValue(Math.round(value*eased));if(progress<1)frame=requestAnimationFrame(animate)};frame=requestAnimationFrame(animate);return()=>cancelAnimationFrame(frame)},[inView,value]);return <span ref={ref}>{displayValue}{suffix}</span>}
function Header(){const [menuOpen,setMenuOpen]=useState(false);const [scrolled,setScrolled]=useState(false);useEffect(()=>{const h=()=>setScrolled(window.scrollY>24);h();window.addEventListener("scroll",h,{passive:true});return()=>window.removeEventListener("scroll",h)},[]);useEffect(()=>{document.body.style.overflow=menuOpen?"hidden":"";return()=>{document.body.style.overflow=""}},[menuOpen]);const closeMenu=()=>setMenuOpen(false);return <><header className={`site-header${scrolled?" site-header--scrolled":""}`}><a href="#home" aria-label="Brix Legal home" onClick={closeMenu}><Brand/></a><nav aria-label="Primary navigation">{navItems.map(item=><a key={item.href} href={item.href}>{item.label}</a>)}</nav><Link className="button button--primary header-booking" href="/consultation">Book Consultation</Link><button className="menu-toggle" type="button" aria-label="Open navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(true)}><Menu size={23}/></button></header><button className={`menu-backdrop${menuOpen?" is-open":""}`} type="button" aria-label="Close navigation" onClick={closeMenu}/><aside className={`mobile-menu${menuOpen?" is-open":""}`} aria-label="Mobile navigation"><div className="mobile-menu__head"><a href="#home" aria-label="Brix Legal home" onClick={closeMenu}><Brand compact/></a><button type="button" aria-label="Close navigation" onClick={closeMenu}><X size={23}/></button></div><nav>{navItems.map(item=><a key={item.href} href={item.href} onClick={closeMenu}>{item.label}</a>)}</nav><Link className="button button--primary" href="/consultation" onClick={closeMenu}>Book Consultation</Link></aside></>}
function Hero(){return <section id="home" className="hero"><div className="hero__copy"><motion.div {...reveal}><SectionLabel>Brix Legal · Est. Nigeria</SectionLabel></motion.div><motion.h1 {...reveal}>For seamless <em>legal practice</em>, built to outlast today.</motion.h1><motion.p {...reveal} className="hero__lead">A multidisciplinary law firm delivering detail-driven corporate, commercial and compliance counsel to local and international clients — with the care of a partner and the precision of a specialist.</motion.p><motion.div {...reveal} className="button-row"><Link className="button button--primary" href="/consultation">Book Consultation <ArrowRight size={17}/></Link><a className="button button--outline" href="#practice">Our Services</a></motion.div><motion.div {...reveal} className="hero__stats"><div><strong>14</strong><span>Areas of practice</span></div><div><strong>2</strong><span>Offices · Abuja &amp; Calabar</span></div><div><strong>100%</strong><span>Client confidentiality</span></div></motion.div></div><motion.div {...reveal} className="hero__visual"><img className="hero__watermark" src="/brix-legal-emblem.webp" alt="" aria-hidden="true"/><div className="hero__portrait"><img className="hero__photo" src="/reference-image-3.webp" alt="Briana A. Akpagu Esq., Principal Partner of Brix Legal"/><div className="hero__identity"><img src="/brix-legal-emblem.webp" alt="" aria-hidden="true"/><span><strong>Briana A. Akpagu</strong><small>Principal Partner · ACArb · DCP</small></span></div></div></motion.div></section>}
function ClientTicker(){const repeatedNames=[...clientNames,...clientNames];return <section className="client-ticker" aria-label="Trusted clients"><p>Trusted by esteemed clients</p><div className="client-ticker__window"><div className="client-ticker__track">{repeatedNames.map((name,index)=><span key={`${name}-${index}`}>{name}</span>)}</div></div></section>}
function AboutFirm(){return <section id="about-firm" className="section about-firm"><SectionLabel>01 About the firm</SectionLabel><div className="about-firm__grid"><motion.p {...reveal} className="about-firm__lead">Brix Legal Practice and Consultancy is a multidisciplinary law firm — providing{" "}<em>informed consultation and excellent legal services</em> to both local and international clients.</motion.p><motion.div {...reveal} className="about-firm__copy"><p>We specialise in corporate practice, statutory compliance, commercial law, real estate, taxation, intellectual property and alternative dispute resolution — combining deep sector experience with a genuinely client-centred approach.</p><p>Our work goes beyond the matter in front of us. We structure your business, assets and agreements to stand the test of time, ensuring what you build outlasts you and transitions seamlessly to those you intend to benefit — legacy building, done right.</p><div className="signature"><strong>Briana A. Akpagu</strong><span>Principal Partner, Brix Legal</span></div></motion.div></div><motion.div {...reveal} className="about-firm__metrics"><div><strong><Counter value={14}/></strong><span>Areas of practice</span></div><div><strong><Counter value={2}/></strong><span>Offices — Abuja &amp; Calabar</span></div><div><strong><Counter value={200} suffix="+"/></strong><span>Esteemed clients served</span></div><div><strong><Counter value={100} suffix="%"/></strong><span>Confidential &amp; privileged</span></div></motion.div></section>}
function WhyBrix(){return <section id="about" className="section section--tint why-brix"><SectionLabel>02 Why Brix Legal</SectionLabel><motion.h2 {...reveal}>The advantages of a firm that treats your matter as its own.</motion.h2><motion.p {...reveal} className="section-intro">We&apos;re here to make your legal process as smooth and hassle-free as possible — because we truly value our clients.</motion.p><div className="reason-grid">{reasons.map(({id,title,description,icon:Icon})=><motion.article key={id} initial={reveal.initial} whileInView={reveal.whileInView} viewport={reveal.viewport} transition={reveal.transition}><span key={`${id}-icon`} className="reason-grid__icon"><Icon size={27} strokeWidth={1.7}/></span><h3 key={`${id}-title`}>{title}</h3><p key={`${id}-description`}>{description}</p></motion.article>)}</div></section>}
function MissionVision(){return <section id="mission" className="section mission"><div className="section-heading section-heading--center"><SectionLabel>03 What drives us</SectionLabel><motion.h2 {...reveal}>Mission &amp; Vision</motion.h2></div><div className="mission__grid"><motion.article {...reveal}><span>◎ &nbsp; Our Mission</span><p>To provide seamless, detail-driven legal services that empower local and international clients to navigate statutory compliance, corporate, commercial and tax laws — while promoting alternative dispute resolution and advancing social justice.</p></motion.article><motion.article {...reveal} className="mission__vision"><span>⚑ &nbsp; Our Vision</span><p>To be a trusted global legal partner known for excellence, innovation and integrity — championing client satisfaction and contributing meaningfully to a just and equitable society.</p></motion.article></div></section>}
function PracticeAreas(){return <section id="practice" className="section section--tint practice"><SectionLabel>04 Expertise &amp; Services</SectionLabel><motion.h2 {...reveal}>Fourteen areas of practice, one standard of care.</motion.h2><motion.p {...reveal} className="section-intro">Multidisciplinary counsel across the matters that shape and protect Nigerian and international businesses.</motion.p><div className="practice__grid">{practiceAreas.map(([title,description],index)=><motion.article {...reveal} key={`practice-${index}-${title}`}><span key={`number-${index}`}>{String(index+1).padStart(2,"0")}</span><div key={`content-${index}`}><h3>{title}</h3><p>{description}</p></div></motion.article>)}</div></section>}
function Process(){return <section id="process" className="section process"><div className="section-heading section-heading--center"><SectionLabel>05 How we work</SectionLabel><motion.h2 {...reveal}>A clear path from first call to lasting outcome.</motion.h2></div><div className="process__steps">{processSteps.map(([number,title,description])=><motion.article {...reveal} key={`process-${number}`}><span key={`process-${number}-number`}>§ {number}</span><h3 key={`process-${number}-title`}>{title}</h3><p key={`process-${number}-description`}>{description}</p></motion.article>)}</div></section>}
function Team(){return <section id="team" className="section section--tint team"><div className="team__principal"><motion.div {...reveal} className="team__portrait"><img src="/reference-image-5.webp" alt="Portrait of Briana A. Akpagu Esq."/></motion.div><motion.div {...reveal} className="team__copy"><SectionLabel>06 Meet the Principal Partner</SectionLabel><h2>Briana A. Akpagu <em>Esq.</em></h2><div className="tag-list"><span>Principal Partner</span><span>ACArb</span><span>DCP</span><span>Corporate &amp; Commercial Law</span></div><p>Briana leads Brix Legal with a commitment to excellence, integrity and seamless client service. An Associate of the Chartered Institute of Arbitrators (ACArb) and a Data Compliance Professional (DCP), her practice spans corporate governance, statutory compliance, taxation and legacy building.</p><p>She helps clients navigate complexity with clarity and confidence — turning legal process into a genuine advantage for the businesses and individuals she represents, at home and abroad.</p><div className="button-row"><a className="button button--outline" href="https://www.linkedin.com/in/brianaakpagu" target="_blank" rel="noreferrer"><Linkedin size={17}/> Connect on LinkedIn</a><Link className="text-link" href="/consultation">Book a consultation <ArrowRight size={17}/></Link></div></motion.div></div><div className="growing-team"><SectionLabel>Growing team</SectionLabel><motion.h2 {...reveal}>Room for exceptional people.</motion.h2><motion.p {...reveal} className="section-intro">As Brix Legal grows, so does our bench. These seats are reserved for dedicated professionals who share our standard.</motion.p><div className="role-grid">{openRoles.map(([role,department])=><motion.article {...reveal} key={role}><h3>{role}</h3><p>{department}</p><span>Position open</span></motion.article>)}</div></div></section>}
function Testimonials(){const [active,setActive]=useState(0);const visible=useMemo(()=>[0,1,2].map(offset=>testimonials[(active+offset)%testimonials.length]),[active]);return <section id="insights" className="section testimonials"><div className="section-heading section-heading--split"><div><SectionLabel>07 Client experiences</SectionLabel><motion.h2 {...reveal}>What our clients say.</motion.h2></div><div className="slider-controls"><button type="button" aria-label="Previous testimonials" onClick={()=>setActive(value=>(value-1+testimonials.length)%testimonials.length)}><ArrowLeft size={18}/></button><button type="button" aria-label="Next testimonials" onClick={()=>setActive(value=>(value+1)%testimonials.length)}><ArrowRight size={18}/></button></div></div><div className="testimonial-grid">{visible.map((testimonial,index)=><motion.article {...reveal} key={`${testimonial.company}-${active}-${index}`}><span className="quote-mark">“</span><p>{testimonial.quote}</p><footer><strong>{testimonial.company}</strong><span>{testimonial.sector}</span></footer></motion.article>)}</div></section>}
function Careers(){return <section id="careers" className="section section--dark careers"><div><SectionLabel>08 Careers</SectionLabel><motion.h2 {...reveal}>Build a legal career with purpose.</motion.h2><motion.p {...reveal}>We&apos;re always interested in thoughtful lawyers and legal professionals who care about detail, integrity and excellent client service.</motion.p></div><motion.div {...reveal} className="careers__action"><a className="button button--light" href="mailto:brixlegal@gmail.com?subject=Career%20Application%20-%20Brix%20Legal">Send your CV <Mail size={17}/></a><span>brixlegal@gmail.com</span></motion.div></section>}
function Contact(){return <section id="contact" className="section contact"><div><SectionLabel>09 Contact</SectionLabel><motion.h2 {...reveal}>Let&apos;s discuss your legal needs.</motion.h2><motion.p {...reveal} className="section-intro">Start with a consultation. We&apos;ll listen carefully, assess the matter and show you the clearest path forward.</motion.p><div className="contact__details"><a href="mailto:brixlegal@gmail.com"><Mail size={18}/> brixlegal@gmail.com</a><a href="https://wa.me/2348093446492" target="_blank" rel="noreferrer"><MessageCircle size={18}/> +234 809 344 6492</a><span><MapPin size={18}/> Abuja · Calabar, Nigeria</span></div></div><motion.div {...reveal} className="contact__card"><h3>Ready when you are.</h3><p>Choose a convenient time and tell us briefly what you need help with.</p><Link className="button button--primary" href="/consultation">Book Consultation <ArrowRight size={17}/></Link></motion.div></section>}
function Footer(){return <footer className="footer"><Brand/><div><a href="#about">About</a><a href="#practice">Practice Areas</a><a href="#team">Team</a><a href="#careers">Careers</a><a href="#contact">Contact</a></div><p>© {new Date().getFullYear()} Brix Legal Practice &amp; Consultancy. All rights reserved.</p></footer>}
function ScrollTop(){const [visible,setVisible]=useState(false);useEffect(()=>{const onScroll=()=>setVisible(window.scrollY>700);onScroll();window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);return <button className={`scroll-top${visible?" is-visible":""}`} type="button" aria-label="Back to top" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}><ChevronUp size={20}/></button>}
export default function Home(){return <main><Header/><Hero/><ClientTicker/><AboutFirm/><WhyBrix/><MissionVision/><PracticeAreas/><Process/><Team/><Testimonials/><Careers/><Contact/><Footer/><ScrollTop/></main>}
