import "server-only";

type ConsultationMail={reference:string;tracking_token?:string|null;full_name:string;email:string;phone?:string;practice_area:string;office:string;consultation_type:string;preferred_date:string;preferred_time:string;status?:string};
type ChangeRequestMail={id:string;request_type:string;requested_date?:string|null;requested_time?:string|null;reason:string;admin_note?:string|null};
const api="https://api.resend.com/emails";
const site=()=>process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/,"")||"http://localhost:3000";
const from=()=>process.env.BRIX_EMAIL_FROM||"Brix Legal <consultations@brixlegal.ng>";
const admin=()=>process.env.BRIX_ADMIN_EMAIL;
function esc(v:string){return v.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]!))}
function shell(title:string,lead:string,body:string,button?:{label:string;url:string}){return `<!doctype html><html><body style="margin:0;background:#f4f1eb;font-family:Arial,sans-serif;color:#16231d"><table width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:42px 16px"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;margin:auto;background:#fff;border:1px solid #e4ded3"><tr><td style="padding:32px 38px;background:#102c24;color:#fff"><div style="font-family:Georgia,serif;font-size:27px">Brix Legal</div><div style="margin-top:5px;font-size:10px;letter-spacing:2px;text-transform:uppercase;color:#d7c7a2">Practice &amp; Consultancy</div></td></tr><tr><td style="padding:38px"><div style="font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#927a4b">Client Services</div><h1 style="font-family:Georgia,serif;font-size:30px;font-weight:400;line-height:1.2;margin:12px 0 14px">${title}</h1><p style="font-size:15px;line-height:1.75;color:#58635e;margin:0 0 25px">${lead}</p>${body}${button?`<p style="margin:30px 0 4px"><a href="${button.url}" style="display:inline-block;background:#173d32;color:#fff;text-decoration:none;padding:14px 20px;font-size:13px">${button.label}</a></p>`:""}</td></tr><tr><td style="padding:20px 38px;border-top:1px solid #eee8dd;font-size:11px;line-height:1.6;color:#7d847f">This message relates to a Brix Legal consultation request. Please do not forward private tracking links or confidential matter information.</td></tr></table></td></tr></table></body></html>`}
function details(c:ConsultationMail){return `<table width="100%" cellspacing="0" cellpadding="0" style="background:#f7f5f0;border:1px solid #e7e1d6"><tr><td style="padding:18px"><b>Reference</b><br>${esc(c.reference)}</td><td style="padding:18px"><b>Legal service</b><br>${esc(c.practice_area)}</td></tr><tr><td style="padding:18px"><b>Requested appointment</b><br>${esc(c.preferred_date)} · ${esc(c.preferred_time)}</td><td style="padding:18px"><b>Consultation</b><br>${esc(c.consultation_type)} · ${esc(c.office)}</td></tr></table>`}
function requestDetails(r:ChangeRequestMail){return `<table width="100%" cellspacing="0" cellpadding="0" style="margin-top:18px;background:#f7f5f0;border:1px solid #e7e1d6"><tr><td style="padding:18px"><b>Request</b><br>${r.request_type==="reschedule"?"Reschedule appointment":"Cancel appointment"}</td>${r.requested_date?`<td style="padding:18px"><b>Requested appointment</b><br>${esc(r.requested_date)} · ${esc(r.requested_time||"")}</td>`:""}</tr><tr><td colspan="2" style="padding:18px"><b>Reason</b><br>${esc(r.reason)}</td></tr>${r.admin_note?`<tr><td colspan="2" style="padding:18px"><b>Brix Legal note</b><br>${esc(r.admin_note)}</td></tr>`:""}</table>`}
async function send(to:string,subject:string,html:string,idempotencyKey:string){const key=process.env.RESEND_API_KEY;if(!key){console.warn("RESEND_API_KEY missing; email skipped.");return {ok:false,error:"RESEND_API_KEY missing"}}const r=await fetch(api,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json","Idempotency-Key":idempotencyKey},body:JSON.stringify({from:from(),to:[to],subject,html})});const payload=await r.json().catch(()=>({}));if(!r.ok){const error=JSON.stringify(payload);console.error("Resend email failed",r.status,error);return {ok:false,error}}return {ok:true,id:typeof payload.id==="string"?payload.id:undefined}}
export async function sendBookingEmails(c:ConsultationMail){const token=c.tracking_token||"";const track=`${site()}/consultation/status?reference=${encodeURIComponent(c.reference)}&token=${encodeURIComponent(token)}`;await Promise.allSettled([send(c.email,`We received your consultation request · ${c.reference}`,shell("Your consultation request has been received.",`Dear ${esc(c.full_name)}, thank you for contacting Brix Legal. Your request is now awaiting review by our team.`,details(c),{label:"Track consultation",url:track}),`booking-client-${c.reference}`),admin()?send(admin()!,`New consultation · ${c.reference}`,shell("A new consultation request is waiting.",`${esc(c.full_name)} submitted a ${esc(c.practice_area)} consultation request.`,details(c),{label:"Open admin dashboard",url:`${site()}/admin`}),`booking-admin-${c.reference}`):Promise.resolve({ok:false})])}
export async function sendConsultationUpdate(c:ConsultationMail,kind:"status"|"reschedule",previousStatus?:string){const track=`${site()}/consultation/status?reference=${encodeURIComponent(c.reference)}&token=${encodeURIComponent(c.tracking_token||"")}`;let title="Your consultation has been updated.";let lead=`Dear ${esc(c.full_name)}, there is an update to your Brix Legal consultation request.`;let subject=`Consultation update · ${c.reference}`;if(kind==="reschedule"){title="Your appointment details have changed.";lead=`Dear ${esc(c.full_name)}, your requested consultation schedule has been updated. Please review the new appointment details below.`;subject=`Appointment updated · ${c.reference}`}else if(c.status==="confirmed"){title="Your consultation is confirmed.";lead=`Dear ${esc(c.full_name)}, Brix Legal has confirmed your consultation. Your appointment details are below.`;subject=`Consultation confirmed · ${c.reference}`}else if(c.status==="under_review"){title="Your request is under review.";lead=`Dear ${esc(c.full_name)}, our team is reviewing your consultation request and matter information.`;subject=`Consultation under review · ${c.reference}`}else if(c.status==="cancelled"||c.status==="declined"){title=`Your consultation was ${c.status}.`;lead=`Dear ${esc(c.full_name)}, the status of your Brix Legal consultation request has changed to ${c.status}.`;subject=`Consultation ${c.status} · ${c.reference}`}else if(c.status==="completed"){title="Your consultation has been completed.";lead=`Dear ${esc(c.full_name)}, your Brix Legal consultation has been marked as completed.`;subject=`Consultation completed · ${c.reference}`}else if(c.status==="no_show"){title="Your consultation was marked as a no-show.";lead=`Dear ${esc(c.full_name)}, our records indicate that the scheduled Brix Legal consultation was not attended. Please contact the firm if you believe this is incorrect or require another appointment.`;subject=`Consultation attendance update · ${c.reference}`}return send(c.email,subject,shell(title,lead,details(c),{label:"View consultation",url:track}),`${kind}-${c.reference}-${c.status||previousStatus||"update"}-${c.preferred_date}-${c.preferred_time}`)}
export async function sendAppointmentReminder(c:ConsultationMail,hours:number){const track=`${site()}/consultation/status?reference=${encodeURIComponent(c.reference)}&token=${encodeURIComponent(c.tracking_token||"")}`;const label=hours===24?"tomorrow":"soon";const subject=`Reminder: your Brix Legal consultation is ${label} · ${c.reference}`;return send(c.email,subject,shell(`Your consultation is ${label}.`,`Dear ${esc(c.full_name)}, this is a reminder about your confirmed Brix Legal consultation.`,details(c),{label:"View appointment",url:track}),`reminder-${hours}h-${c.reference}-${c.preferred_date}-${c.preferred_time}`)}
export async function sendChangeRequestAdminAlert(c:ConsultationMail,r:ChangeRequestMail){if(!admin())return {ok:false,error:"BRIX_ADMIN_EMAIL missing"};const label=r.request_type==="reschedule"?"reschedule":"cancellation";return send(admin()!,`Client ${label} request · ${c.reference}`,shell(`A client requested ${label}.`,`${esc(c.full_name)} has submitted an appointment change request that requires review.`,details(c)+requestDetails(r),{label:"Review consultation",url:`${site()}/admin/consultations/${(c as any).id||""}`}),`change-request-admin-${r.id}`)}
export async function sendChangeRequestDecision(c:ConsultationMail,r:ChangeRequestMail,decision:"approved"|"declined"){const track=`${site()}/consultation/status?reference=${encodeURIComponent(c.reference)}&token=${encodeURIComponent(c.tracking_token||"")}`;const label=r.request_type==="reschedule"?"reschedule":"cancellation";const title=decision==="approved"?`Your ${label} request was approved.`:`Your ${label} request was declined.`;const lead=decision==="approved"?`Dear ${esc(c.full_name)}, Brix Legal has approved your ${label} request.`:`Dear ${esc(c.full_name)}, Brix Legal reviewed your ${label} request and has not approved the requested change. Your existing appointment remains in place unless otherwise stated below.`;return send(c.email,`${label[0].toUpperCase()+label.slice(1)} request ${decision} · ${c.reference}`,shell(title,lead,details(c)+requestDetails(r),{label:"View consultation",url:track}),`change-request-${decision}-${r.id}`)}
