"use client";
import { useEffect, useState } from "react";
import { CalendarOff, Clock3, Plus, Trash2 } from "lucide-react";
import { createClient } from "../../../lib/supabase/client";

const days=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
type Rule={id:string;weekday:number;start_time:string;end_time:string;slot_minutes:number;office:string|null;consultation_type:string|null;is_active:boolean};
type Block={id:string;blocked_date:string;reason:string|null};
export default function AvailabilityManager(){
 const supabase=createClient(); const [rules,setRules]=useState<Rule[]>([]);const [blocks,setBlocks]=useState<Block[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [rule,setRule]=useState({weekday:1,start_time:"09:00",end_time:"17:00",slot_minutes:60,office:"",consultation_type:""});const [block,setBlock]=useState({blocked_date:"",reason:""});
 const load=async()=>{const [{data:r},{data:b}]=await Promise.all([supabase.from("availability").select("*").order("weekday").order("start_time"),supabase.from("blocked_dates").select("*").order("blocked_date")]);setRules((r??[]) as Rule[]);setBlocks((b??[]) as Block[])};
 useEffect(()=>{load()},[]);
 const toast=(m:string)=>{setMessage(m);setTimeout(()=>setMessage(""),3000)};
 const addRule=async()=>{setBusy(true);const {error}=await supabase.from("availability").insert({...rule,office:rule.office||null,consultation_type:rule.consultation_type||null});setBusy(false);if(error)return toast(error.message);toast("Availability added.");load()};
 const removeRule=async(id:string)=>{const {error}=await supabase.from("availability").delete().eq("id",id);if(error)return toast(error.message);toast("Availability removed.");load()};
 const addBlock=async()=>{if(!block.blocked_date)return toast("Choose a date first.");setBusy(true);const {error}=await supabase.from("blocked_dates").insert(block);setBusy(false);if(error)return toast(error.message);setBlock({blocked_date:"",reason:""});toast("Date blocked.");load()};
 const removeBlock=async(id:string)=>{const {error}=await supabase.from("blocked_dates").delete().eq("id",id);if(error)return toast(error.message);toast("Blocked date removed.");load()};
 return <div className="availability-grid">{message&&<div className="admin-toast">{message}</div>}<section className="admin-table-card"><div className="admin-section-head"><div><span className="consult-panel__eyebrow">Weekly schedule</span><h2>Consultation hours</h2></div><Clock3/></div><div className="availability-form"><select value={rule.weekday} onChange={e=>setRule({...rule,weekday:+e.target.value})}>{days.map((d,i)=><option key={d} value={i}>{d}</option>)}</select><input type="time" value={rule.start_time} onChange={e=>setRule({...rule,start_time:e.target.value})}/><input type="time" value={rule.end_time} onChange={e=>setRule({...rule,end_time:e.target.value})}/><select value={rule.slot_minutes} onChange={e=>setRule({...rule,slot_minutes:+e.target.value})}><option value={30}>30 min</option><option value={45}>45 min</option><option value={60}>60 min</option><option value={90}>90 min</option></select><select value={rule.office} onChange={e=>setRule({...rule,office:e.target.value})}><option value="">All offices</option><option>Abuja</option><option>Calabar</option><option>Remote consultation</option></select><select value={rule.consultation_type} onChange={e=>setRule({...rule,consultation_type:e.target.value})}><option value="">All consultation types</option><option>In person</option><option>Video call</option><option>Phone call</option></select><button className="button button--primary" disabled={busy} onClick={addRule}><Plus size={16}/> Add hours</button></div><div className="availability-list">{rules.map(r=><article key={r.id}><div><strong>{days[r.weekday]} · {r.start_time.slice(0,5)}–{r.end_time.slice(0,5)}</strong><span>{r.slot_minutes} min slots · {r.office||"All offices"} · {r.consultation_type||"All types"}</span></div><button onClick={()=>removeRule(r.id)} aria-label="Remove availability"><Trash2 size={17}/></button></article>)}</div></section><section className="admin-table-card"><div className="admin-section-head"><div><span className="consult-panel__eyebrow">Exceptions</span><h2>Blocked dates</h2></div><CalendarOff/></div><div className="block-form"><input type="date" value={block.blocked_date} onChange={e=>setBlock({...block,blocked_date:e.target.value})}/><input placeholder="Reason, e.g. Public holiday" value={block.reason} onChange={e=>setBlock({...block,reason:e.target.value})}/><button className="button button--primary" disabled={busy} onClick={addBlock}><Plus size={16}/> Block date</button></div><div className="availability-list">{blocks.length===0?<p className="admin-muted">No dates are currently blocked.</p>:blocks.map(b=><article key={b.id}><div><strong>{new Date(`${b.blocked_date}T12:00:00`).toLocaleDateString("en-NG",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}</strong><span>{b.reason||"Unavailable"}</span></div><button onClick={()=>removeBlock(b.id)} aria-label="Remove blocked date"><Trash2 size={17}/></button></article>)}</div></section></div>
}
